.TH "src/cropequ.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cropequ.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBcropequ\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBcrop\fP (pfm, ngpr, ngpz, rgr, nr, zgr, nz, nrn, rmin, rmax, nzn, zmin, zmax)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer \fBcropequ::ngpr\fP"
.br
.ti -1c
.RI "integer \fBcropequ::ngpz\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBcropequ::pfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBcropequ::rgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBcropequ::zgr\fP"
.br
.ti -1c
.RI "real *8 \fBcropequ::rcntc\fP"
.br
.ti -1c
.RI "real *8 \fBcropequ::psimin\fP"
.br
.ti -1c
.RI "real *8 \fBcropequ::psilim\fP"
.br
.ti -1c
.RI "real *8 \fBcropequ::btorc\fP"
.br
.ti -1c
.RI "real *8 \fBcropequ::rmin\fP"
.br
.ti -1c
.RI "real *8 \fBcropequ::rmax\fP"
.br
.ti -1c
.RI "real *8 \fBcropequ::zmin\fP"
.br
.ti -1c
.RI "real *8 \fBcropequ::zmax\fP"
.br
.ti -1c
.RI "integer \fBcropequ::i\fP"
.br
.ti -1c
.RI "integer \fBcropequ::j\fP"
.br
.ti -1c
.RI "integer \fBcropequ::nr\fP"
.br
.ti -1c
.RI "integer \fBcropequ::nz\fP"
.br
.ti -1c
.RI "integer \fBcropequ::nrn\fP"
.br
.ti -1c
.RI "integer \fBcropequ::nzn\fP"
.br
.ti -1c
.RI "integer \fBcropequ::iret\fP"
.br
.ti -1c
.RI "logical \fBcropequ::err\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "subroutine crop (real*8,dimension(ngpr,ngpz) pfm, integer ngpr, integer ngpz, real*8,dimension(ngpr) rgr, integer nr, real*8,dimension(ngpz) zgr, integer nz, integer nrn, real*8 rmin, real*8 rmax, integer nzn, real*8 zmin, real*8 zmax)"
.PP
Definition at line 82 of file cropequ.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
