.TH "cropequ" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cropequ \- Crop the equilibrium.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "integer \fBngpr\fP"
.br
.ti -1c
.RI "integer \fBngpz\fP"
.br
.ti -1c
.RI "real *8, dimension(\fBngpr\fP, \fBngpz\fP) \fBpfm\fP"
.br
.ti -1c
.RI "real *8, dimension(\fBngpr\fP) \fBrgr\fP"
.br
.ti -1c
.RI "real *8, dimension(\fBngpz\fP) \fBzgr\fP"
.br
.ti -1c
.RI "real *8 \fBrcntc\fP"
.br
.ti -1c
.RI "real *8 \fBpsimin\fP"
.br
.ti -1c
.RI "real *8 \fBpsilim\fP"
.br
.ti -1c
.RI "real *8 \fBbtorc\fP"
.br
.ti -1c
.RI "real *8 \fBrmin\fP"
.br
.ti -1c
.RI "real *8 \fBrmax\fP"
.br
.ti -1c
.RI "real *8 \fBzmin\fP"
.br
.ti -1c
.RI "real *8 \fBzmax\fP"
.br
.ti -1c
.RI "integer \fBi\fP"
.br
.ti -1c
.RI "integer \fBj\fP"
.br
.ti -1c
.RI "integer \fBnr\fP"
.br
.ti -1c
.RI "integer \fBnz\fP"
.br
.ti -1c
.RI "integer \fBnrn\fP"
.br
.ti -1c
.RI "integer \fBnzn\fP"
.br
.ti -1c
.RI "integer \fBiret\fP"
.br
.ti -1c
.RI "logical \fBerr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Crop the equilibrium. 

arg1: input equilibrium file name
.PP
arg2: output equilibrium file name
.PP
reads data from standard input
.PP
\fBVersion:\fP
.RS 4
21.07.2000 16:44 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "real*8 \fBcropequ::btorc\fP"
.PP
Definition at line 19 of file cropequ.f.
.SS "logical \fBcropequ::err\fP"
.PP
Definition at line 21 of file cropequ.f.
.SS "integer \fBcropequ::i\fP"
.PP
Definition at line 20 of file cropequ.f.
.SS "integer \fBcropequ::iret\fP"
.PP
Definition at line 20 of file cropequ.f.
.SS "integer \fBcropequ::j\fP"
.PP
Definition at line 20 of file cropequ.f.
.SS "integer \fBcropequ::ngpr\fP"
.PP
Definition at line 16 of file cropequ.f.
.SS "integer \fBcropequ::ngpz\fP"
.PP
Definition at line 16 of file cropequ.f.
.SS "integer \fBcropequ::nr\fP"
.PP
Definition at line 20 of file cropequ.f.
.SS "integer \fBcropequ::nrn\fP"
.PP
Definition at line 20 of file cropequ.f.
.SS "integer \fBcropequ::nz\fP"
.PP
Definition at line 20 of file cropequ.f.
.SS "integer \fBcropequ::nzn\fP"
.PP
Definition at line 20 of file cropequ.f.
.SS "real*8,dimension(\fBngpr\fP,\fBngpz\fP) \fBcropequ::pfm\fP"
.PP
Definition at line 18 of file cropequ.f.
.SS "real*8 \fBcropequ::psilim\fP"
.PP
Definition at line 19 of file cropequ.f.
.SS "real*8 \fBcropequ::psimin\fP"
.PP
Definition at line 19 of file cropequ.f.
.SS "real*8 \fBcropequ::rcntc\fP"
.PP
Definition at line 19 of file cropequ.f.
.SS "real*8,dimension(\fBngpr\fP) \fBcropequ::rgr\fP"
.PP
Definition at line 18 of file cropequ.f.
.SS "real*8 \fBcropequ::rmax\fP"
.PP
Definition at line 19 of file cropequ.f.
.SS "real*8 \fBcropequ::rmin\fP"
.PP
Definition at line 19 of file cropequ.f.
.SS "real*8,dimension(\fBngpz\fP) \fBcropequ::zgr\fP"
.PP
Definition at line 18 of file cropequ.f.
.SS "real*8 \fBcropequ::zmax\fP"
.PP
Definition at line 19 of file cropequ.f.
.SS "real*8 \fBcropequ::zmin\fP"
.PP
Definition at line 19 of file cropequ.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
