.TH "src/culham.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/culham.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBculham\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr) \fBculham::fg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBculham::pg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBculham::ffg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBculham::ppg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBculham::pfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBculham::rgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBculham::zgr\fP"
.br
.ti -1c
.RI "real *8 \fBculham::rdim\fP"
.br
.ti -1c
.RI "real *8 \fBculham::zdim\fP"
.br
.ti -1c
.RI "real *8 \fBculham::rcntc\fP"
.br
.ti -1c
.RI "real *8 \fBculham::redge\fP"
.br
.ti -1c
.RI "real *8 \fBculham::zmsmid\fP"
.br
.ti -1c
.RI "real *8 \fBculham::rma\fP"
.br
.ti -1c
.RI "real *8 \fBculham::zma\fP"
.br
.ti -1c
.RI "real *8 \fBculham::psimin\fP"
.br
.ti -1c
.RI "real *8 \fBculham::psilim\fP"
.br
.ti -1c
.RI "real *8 \fBculham::btorc\fP"
.br
.ti -1c
.RI "character \fBculham::title\fP"
.br
.ti -1c
.RI "character \fBculham::date\fP"
.br
.ti -1c
.RI "integer \fBculham::chop\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
