.TH "culham" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
culham \- Translation of efit equilibrium data into dg-compatible format.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr) \fBfg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBpg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBffg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBppg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBpfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBrgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBzgr\fP"
.br
.ti -1c
.RI "real *8 \fBrdim\fP"
.br
.ti -1c
.RI "real *8 \fBzdim\fP"
.br
.ti -1c
.RI "real *8 \fBrcntc\fP"
.br
.ti -1c
.RI "real *8 \fBredge\fP"
.br
.ti -1c
.RI "real *8 \fBzmsmid\fP"
.br
.ti -1c
.RI "real *8 \fBrma\fP"
.br
.ti -1c
.RI "real *8 \fBzma\fP"
.br
.ti -1c
.RI "real *8 \fBpsimin\fP"
.br
.ti -1c
.RI "real *8 \fBpsilim\fP"
.br
.ti -1c
.RI "real *8 \fBbtorc\fP"
.br
.ti -1c
.RI "character \fBtitle\fP"
.br
.ti -1c
.RI "character \fBdate\fP"
.br
.ti -1c
.RI "integer \fBchop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Translation of efit equilibrium data into dg-compatible format. 

arg1: input equilibrium file name
.PP
arg2: output equilibrium file name
.PP
This is a special variant of the standard efit-to-dg converter for Culham. A number of columns of the flux matrix are removed, and the resolution is quadrupled in each direction using splines.
.PP
\fBVersion:\fP
.RS 4
16.11.95 20:04 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "real*8 \fBculham::btorc\fP"
.PP
Definition at line 23 of file culham.f.
.SS "integer \fBculham::chop\fP"
.PP
Definition at line 25 of file culham.f.
.SS "character \fBculham::date\fP"
.PP
Definition at line 24 of file culham.f.
.SS "real*8,dimension(ngpr) \fBculham::ffg\fP"
.PP
Definition at line 21 of file culham.f.
.SS "real*8,dimension(ngpr) \fBculham::fg\fP"
.PP
Definition at line 21 of file culham.f.
.SS "real*8,dimension(ngpr,ngpz) \fBculham::pfm\fP"
.PP
Definition at line 22 of file culham.f.
.SS "real*8,dimension(ngpr) \fBculham::pg\fP"
.PP
Definition at line 21 of file culham.f.
.SS "real*8,dimension(ngpr) \fBculham::ppg\fP"
.PP
Definition at line 21 of file culham.f.
.SS "real*8 \fBculham::psilim\fP"
.PP
Definition at line 23 of file culham.f.
.SS "real*8 \fBculham::psimin\fP"
.PP
Definition at line 23 of file culham.f.
.SS "real*8 \fBculham::rcntc\fP"
.PP
Definition at line 23 of file culham.f.
.SS "real*8 \fBculham::rdim\fP"
.PP
Definition at line 23 of file culham.f.
.SS "real*8 \fBculham::redge\fP"
.PP
Definition at line 23 of file culham.f.
.SS "real*8,dimension(ngpr) \fBculham::rgr\fP"
.PP
Definition at line 22 of file culham.f.
.SS "real*8 \fBculham::rma\fP"
.PP
Definition at line 23 of file culham.f.
.SS "character \fBculham::title\fP"
.PP
Definition at line 24 of file culham.f.
.SS "real*8 \fBculham::zdim\fP"
.PP
Definition at line 23 of file culham.f.
.SS "real*8,dimension(ngpz) \fBculham::zgr\fP"
.PP
Definition at line 22 of file culham.f.
.SS "real*8 \fBculham::zma\fP"
.PP
Definition at line 23 of file culham.f.
.SS "real*8 \fBculham::zmsmid\fP"
.PP
Definition at line 23 of file culham.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
