.TH "src/dg2dg.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dg2dg.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBdg2dg\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer \fBdg2dg::ngpr\fP"
.br
.ti -1c
.RI "integer \fBdg2dg::ngpz\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBdg2dg::pfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBdg2dg::rgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBdg2dg::zgr\fP"
.br
.ti -1c
.RI "real *8 \fBdg2dg::rcntc\fP"
.br
.ti -1c
.RI "real *8 \fBdg2dg::psimin\fP"
.br
.ti -1c
.RI "real *8 \fBdg2dg::psilim\fP"
.br
.ti -1c
.RI "real *8 \fBdg2dg::btorc\fP"
.br
.ti -1c
.RI "integer \fBdg2dg::nr\fP"
.br
.ti -1c
.RI "integer \fBdg2dg::nz\fP"
.br
.ti -1c
.RI "integer \fBdg2dg::iret\fP"
.br
.ti -1c
.RI "integer \fBdg2dg::i\fP"
.br
.ti -1c
.RI "integer \fBdg2dg::j\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
