.TH "dg2ef" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dg2ef \- Translation of dg-compatible equilibrium data into efit format.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr) \fBfg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBpg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBffg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBppg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBpfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBrgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBzgr\fP"
.br
.ti -1c
.RI "real *8 \fBrdim\fP"
.br
.ti -1c
.RI "real *8 \fBzdim\fP"
.br
.ti -1c
.RI "real *8 \fBrcntc\fP"
.br
.ti -1c
.RI "real *8 \fBredge\fP"
.br
.ti -1c
.RI "real *8 \fBzmsmid\fP"
.br
.ti -1c
.RI "real *8 \fBrma\fP"
.br
.ti -1c
.RI "real *8 \fBzma\fP"
.br
.ti -1c
.RI "real *8 \fBpsimin\fP"
.br
.ti -1c
.RI "real *8 \fBpsilim\fP"
.br
.ti -1c
.RI "real *8 \fBbtorc\fP"
.br
.ti -1c
.RI "character \fBtitle\fP"
.br
.ti -1c
.RI "character \fBdate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Translation of dg-compatible equilibrium data into efit format. 

arg1: input equilibrium file name
.PP
arg2: output equilibrium file name
.PP
\fBVersion:\fP
.RS 4
02.09.99 14:19 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "real*8 \fBdg2ef::btorc\fP"
.PP
Definition at line 19 of file dg2ef.f.
.SS "character \fBdg2ef::date\fP"
.PP
Definition at line 20 of file dg2ef.f.
.SS "real*8,dimension(ngpr) \fBdg2ef::ffg\fP"
.PP
Definition at line 17 of file dg2ef.f.
.SS "real*8,dimension(ngpr) \fBdg2ef::fg\fP"
.PP
Definition at line 17 of file dg2ef.f.
.SS "real*8,dimension(ngpr,ngpz) \fBdg2ef::pfm\fP"
.PP
Definition at line 18 of file dg2ef.f.
.SS "real*8,dimension(ngpr) \fBdg2ef::pg\fP"
.PP
Definition at line 17 of file dg2ef.f.
.SS "real*8,dimension(ngpr) \fBdg2ef::ppg\fP"
.PP
Definition at line 17 of file dg2ef.f.
.SS "real*8 \fBdg2ef::psilim\fP"
.PP
Definition at line 19 of file dg2ef.f.
.SS "real*8 \fBdg2ef::psimin\fP"
.PP
Definition at line 19 of file dg2ef.f.
.SS "real*8 \fBdg2ef::rcntc\fP"
.PP
Definition at line 19 of file dg2ef.f.
.SS "real*8 \fBdg2ef::rdim\fP"
.PP
Definition at line 19 of file dg2ef.f.
.SS "real*8 \fBdg2ef::redge\fP"
.PP
Definition at line 19 of file dg2ef.f.
.SS "real*8,dimension(ngpr) \fBdg2ef::rgr\fP"
.PP
Definition at line 18 of file dg2ef.f.
.SS "real*8 \fBdg2ef::rma\fP"
.PP
Definition at line 19 of file dg2ef.f.
.SS "character \fBdg2ef::title\fP"
.PP
Definition at line 20 of file dg2ef.f.
.SS "real*8 \fBdg2ef::zdim\fP"
.PP
Definition at line 19 of file dg2ef.f.
.SS "real*8,dimension(ngpz) \fBdg2ef::zgr\fP"
.PP
Definition at line 18 of file dg2ef.f.
.SS "real*8 \fBdg2ef::zma\fP"
.PP
Definition at line 19 of file dg2ef.f.
.SS "real*8 \fBdg2ef::zmsmid\fP"
.PP
Definition at line 19 of file dg2ef.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
