.TH "src/dg2ef.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dg2ef.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBdg2ef\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr) \fBdg2ef::fg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBdg2ef::pg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBdg2ef::ffg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBdg2ef::ppg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBdg2ef::pfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBdg2ef::rgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBdg2ef::zgr\fP"
.br
.ti -1c
.RI "real *8 \fBdg2ef::rdim\fP"
.br
.ti -1c
.RI "real *8 \fBdg2ef::zdim\fP"
.br
.ti -1c
.RI "real *8 \fBdg2ef::rcntc\fP"
.br
.ti -1c
.RI "real *8 \fBdg2ef::redge\fP"
.br
.ti -1c
.RI "real *8 \fBdg2ef::zmsmid\fP"
.br
.ti -1c
.RI "real *8 \fBdg2ef::rma\fP"
.br
.ti -1c
.RI "real *8 \fBdg2ef::zma\fP"
.br
.ti -1c
.RI "real *8 \fBdg2ef::psimin\fP"
.br
.ti -1c
.RI "real *8 \fBdg2ef::psilim\fP"
.br
.ti -1c
.RI "real *8 \fBdg2ef::btorc\fP"
.br
.ti -1c
.RI "character \fBdg2ef::title\fP"
.br
.ti -1c
.RI "character \fBdg2ef::date\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
