.TH "dg2vr" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dg2vr \- Translation of TdeV equilibrium data into dg-compatible format.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBpfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBrgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBzgr\fP"
.br
.ti -1c
.RI "real *8 \fBrcntc\fP"
.br
.ti -1c
.RI "real *8 \fBpsilim\fP"
.br
.ti -1c
.RI "real *8 \fBbtorc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Translation of TdeV equilibrium data into dg-compatible format. 

arg1: input equilibrium file name
.PP
arg2: output equilibrium file name
.PP
\fBVersion:\fP
.RS 4
30.01.96 21:59 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "real*8 \fBdg2vr::btorc\fP"
.PP
Definition at line 18 of file dg2vr.f.
.SS "real*8,dimension(ngpr,ngpz) \fBdg2vr::pfm\fP"
.PP
Definition at line 17 of file dg2vr.f.
.SS "real*8 \fBdg2vr::psilim\fP"
.PP
Definition at line 18 of file dg2vr.f.
.SS "real*8 \fBdg2vr::rcntc\fP"
.PP
Definition at line 18 of file dg2vr.f.
.SS "real*8,dimension(ngpr) \fBdg2vr::rgr\fP"
.PP
Definition at line 17 of file dg2vr.f.
.SS "real*8,dimension(ngpz) \fBdg2vr::zgr\fP"
.PP
Definition at line 17 of file dg2vr.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
