.TH "src/dg2vr.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dg2vr.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBdg2vr\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBdg2vr::pfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBdg2vr::rgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBdg2vr::zgr\fP"
.br
.ti -1c
.RI "real *8 \fBdg2vr::rcntc\fP"
.br
.ti -1c
.RI "real *8 \fBdg2vr::psilim\fP"
.br
.ti -1c
.RI "real *8 \fBdg2vr::btorc\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
