.TH "src/dg_arith_dg.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dg_arith_dg.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBdg_arith_dg\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBdg_arith_dg::pfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBdg_arith_dg::rgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBdg_arith_dg::zgr\fP"
.br
.ti -1c
.RI "real *8 \fBdg_arith_dg::rcntc\fP"
.br
.ti -1c
.RI "real *8 \fBdg_arith_dg::psilim\fP"
.br
.ti -1c
.RI "real *8 \fBdg_arith_dg::btorc\fP"
.br
.ti -1c
.RI "real *8 \fBdg_arith_dg::shift\fP"
.br
.ti -1c
.RI "character *256 \fBdg_arith_dg::filename\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
