.TH "dg_minuspsi_dg" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dg_minuspsi_dg \- Change the sign of the flux.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBpfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBrgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBzgr\fP"
.br
.ti -1c
.RI "real *8 \fBrcntc\fP"
.br
.ti -1c
.RI "real *8 \fBpsilim\fP"
.br
.ti -1c
.RI "real *8 \fBbtorc\fP"
.br
.ti -1c
.RI "real *8 \fBshift\fP"
.br
.ti -1c
.RI "character *256 \fBfilename\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Change the sign of the flux. 

arg1: input equilibrium file name
.PP
arg2: output equilibrium file name
.PP
\fBVersion:\fP
.RS 4
30.01.96 21:58 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "real*8 \fBdg_minuspsi_dg::btorc\fP"
.PP
Definition at line 18 of file dg_minuspsi_dg.f.
.SS "character*256 \fBdg_minuspsi_dg::filename\fP"
.PP
Definition at line 19 of file dg_minuspsi_dg.f.
.SS "real*8,dimension(ngpr,ngpz) \fBdg_minuspsi_dg::pfm\fP"
.PP
Definition at line 17 of file dg_minuspsi_dg.f.
.SS "real*8 \fBdg_minuspsi_dg::psilim\fP"
.PP
Definition at line 18 of file dg_minuspsi_dg.f.
.SS "real*8 \fBdg_minuspsi_dg::rcntc\fP"
.PP
Definition at line 18 of file dg_minuspsi_dg.f.
.SS "real*8,dimension(ngpr) \fBdg_minuspsi_dg::rgr\fP"
.PP
Definition at line 17 of file dg_minuspsi_dg.f.
.SS "real*8 \fBdg_minuspsi_dg::shift\fP"
.PP
Definition at line 18 of file dg_minuspsi_dg.f.
.SS "real*8,dimension(ngpz) \fBdg_minuspsi_dg::zgr\fP"
.PP
Definition at line 17 of file dg_minuspsi_dg.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
