.TH "src/diva2dg.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/diva2dg.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBdiva2dg\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr) \fBdiva2dg::gpr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBdiva2dg::gpz\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpf) \fBdiva2dg::pfl\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpf) \fBdiva2dg::pc\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpf) \fBdiva2dg::pcd\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpf) \fBdiva2dg::pr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpf) \fBdiva2dg::prd\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpf) \fBdiva2dg::q\fP"
.br
.ti -1c
.RI "real *8, dimension(3) \fBdiva2dg::apf\fP"
.br
.ti -1c
.RI "real *8, dimension(3) \fBdiva2dg::xpf\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBdiva2dg::pfm\fP"
.br
.ti -1c
.RI "real *8 \fBdiva2dg::rcntc\fP"
.br
.ti -1c
.RI "real *8 \fBdiva2dg::btorc\fP"
.br
.ti -1c
.RI "real *8 \fBdiva2dg::Bt\fP"
.br
.ti -1c
.RI "real *8, dimension(6) \fBdiva2dg::derivative\fP"
.br
.ti -1c
.RI "character *256 \fBdiva2dg::filename\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
