.TH "ef2dg" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ef2dg \- Translation of efit equilibrium data into dg-compatible format.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr) \fBfg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBpg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBffg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBppg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBpfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBrgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBzgr\fP"
.br
.ti -1c
.RI "real *8 \fBrdim\fP"
.br
.ti -1c
.RI "real *8 \fBzdim\fP"
.br
.ti -1c
.RI "real *8 \fBrcntc\fP"
.br
.ti -1c
.RI "real *8 \fBredge\fP"
.br
.ti -1c
.RI "real *8 \fBzmsmid\fP"
.br
.ti -1c
.RI "real *8 \fBrma\fP"
.br
.ti -1c
.RI "real *8 \fBzma\fP"
.br
.ti -1c
.RI "real *8 \fBpsimin\fP"
.br
.ti -1c
.RI "real *8 \fBpsilim\fP"
.br
.ti -1c
.RI "real *8 \fBbtorc\fP"
.br
.ti -1c
.RI "character \fBtitle\fP"
.br
.ti -1c
.RI "character \fBdate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Translation of efit equilibrium data into dg-compatible format. 

arg1: input equilibrium file name
.PP
arg2: output equilibrium file name
.PP
\fBVersion:\fP
.RS 4
16.11.95 20:04 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "real*8 \fBef2dg::btorc\fP"
.PP
Definition at line 19 of file ef2dg.f.
.SS "character \fBef2dg::date\fP"
.PP
Definition at line 20 of file ef2dg.f.
.SS "real*8,dimension(ngpr) \fBef2dg::ffg\fP"
.PP
Definition at line 17 of file ef2dg.f.
.SS "real*8,dimension(ngpr) \fBef2dg::fg\fP"
.PP
Definition at line 17 of file ef2dg.f.
.SS "real*8,dimension(ngpr,ngpz) \fBef2dg::pfm\fP"
.PP
Definition at line 18 of file ef2dg.f.
.SS "real*8,dimension(ngpr) \fBef2dg::pg\fP"
.PP
Definition at line 17 of file ef2dg.f.
.SS "real*8,dimension(ngpr) \fBef2dg::ppg\fP"
.PP
Definition at line 17 of file ef2dg.f.
.SS "real*8 \fBef2dg::psilim\fP"
.PP
Definition at line 19 of file ef2dg.f.
.SS "real*8 \fBef2dg::psimin\fP"
.PP
Definition at line 19 of file ef2dg.f.
.SS "real*8 \fBef2dg::rcntc\fP"
.PP
Definition at line 19 of file ef2dg.f.
.SS "real*8 \fBef2dg::rdim\fP"
.PP
Definition at line 19 of file ef2dg.f.
.SS "real*8 \fBef2dg::redge\fP"
.PP
Definition at line 19 of file ef2dg.f.
.SS "real*8,dimension(ngpr) \fBef2dg::rgr\fP"
.PP
Definition at line 18 of file ef2dg.f.
.SS "real*8 \fBef2dg::rma\fP"
.PP
Definition at line 19 of file ef2dg.f.
.SS "character \fBef2dg::title\fP"
.PP
Definition at line 20 of file ef2dg.f.
.SS "real*8 \fBef2dg::zdim\fP"
.PP
Definition at line 19 of file ef2dg.f.
.SS "real*8,dimension(ngpz) \fBef2dg::zgr\fP"
.PP
Definition at line 18 of file ef2dg.f.
.SS "real*8 \fBef2dg::zma\fP"
.PP
Definition at line 19 of file ef2dg.f.
.SS "real*8 \fBef2dg::zmsmid\fP"
.PP
Definition at line 19 of file ef2dg.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
