.TH "src/jt2dg.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/jt2dg.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBjt2dg\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr) \fBjt2dg::fg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBjt2dg::pg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBjt2dg::ffg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBjt2dg::ppg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBjt2dg::pfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBjt2dg::rgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBjt2dg::zgr\fP"
.br
.ti -1c
.RI "real *8 \fBjt2dg::rdim\fP"
.br
.ti -1c
.RI "real *8 \fBjt2dg::zdim\fP"
.br
.ti -1c
.RI "real *8 \fBjt2dg::rcntc\fP"
.br
.ti -1c
.RI "real *8 \fBjt2dg::redge\fP"
.br
.ti -1c
.RI "real *8 \fBjt2dg::zmsmid\fP"
.br
.ti -1c
.RI "real *8 \fBjt2dg::rma\fP"
.br
.ti -1c
.RI "real *8 \fBjt2dg::zma\fP"
.br
.ti -1c
.RI "real *8 \fBjt2dg::psimin\fP"
.br
.ti -1c
.RI "real *8 \fBjt2dg::psilim\fP"
.br
.ti -1c
.RI "real *8 \fBjt2dg::btorc\fP"
.br
.ti -1c
.RI "character \fBjt2dg::title\fP"
.br
.ti -1c
.RI "character \fBjt2dg::date\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
