.TH "jt2dg" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jt2dg \- Translation of efit equilibrium data into dg-compatible format.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr) \fBfg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBpg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBffg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBppg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBpfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBrgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBzgr\fP"
.br
.ti -1c
.RI "real *8 \fBrdim\fP"
.br
.ti -1c
.RI "real *8 \fBzdim\fP"
.br
.ti -1c
.RI "real *8 \fBrcntc\fP"
.br
.ti -1c
.RI "real *8 \fBredge\fP"
.br
.ti -1c
.RI "real *8 \fBzmsmid\fP"
.br
.ti -1c
.RI "real *8 \fBrma\fP"
.br
.ti -1c
.RI "real *8 \fBzma\fP"
.br
.ti -1c
.RI "real *8 \fBpsimin\fP"
.br
.ti -1c
.RI "real *8 \fBpsilim\fP"
.br
.ti -1c
.RI "real *8 \fBbtorc\fP"
.br
.ti -1c
.RI "character \fBtitle\fP"
.br
.ti -1c
.RI "character \fBdate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Translation of efit equilibrium data into dg-compatible format. 

arg1: input equilibrium file name
.PP
arg2: output equilibrium file name
.PP
\fBVersion:\fP
.RS 4
09.07.97 17:14 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "real*8 \fBjt2dg::btorc\fP"
.PP
Definition at line 19 of file jt2dg.f.
.SS "character \fBjt2dg::date\fP"
.PP
Definition at line 20 of file jt2dg.f.
.SS "real*8,dimension(ngpr) \fBjt2dg::ffg\fP"
.PP
Definition at line 17 of file jt2dg.f.
.SS "real*8,dimension(ngpr) \fBjt2dg::fg\fP"
.PP
Definition at line 17 of file jt2dg.f.
.SS "real*8,dimension(ngpr,ngpz) \fBjt2dg::pfm\fP"
.PP
Definition at line 18 of file jt2dg.f.
.SS "real*8,dimension(ngpr) \fBjt2dg::pg\fP"
.PP
Definition at line 17 of file jt2dg.f.
.SS "real*8,dimension(ngpr) \fBjt2dg::ppg\fP"
.PP
Definition at line 17 of file jt2dg.f.
.SS "real*8 \fBjt2dg::psilim\fP"
.PP
Definition at line 19 of file jt2dg.f.
.SS "real*8 \fBjt2dg::psimin\fP"
.PP
Definition at line 19 of file jt2dg.f.
.SS "real*8 \fBjt2dg::rcntc\fP"
.PP
Definition at line 19 of file jt2dg.f.
.SS "real*8 \fBjt2dg::rdim\fP"
.PP
Definition at line 19 of file jt2dg.f.
.SS "real*8 \fBjt2dg::redge\fP"
.PP
Definition at line 19 of file jt2dg.f.
.SS "real*8,dimension(ngpr) \fBjt2dg::rgr\fP"
.PP
Definition at line 18 of file jt2dg.f.
.SS "real*8 \fBjt2dg::rma\fP"
.PP
Definition at line 19 of file jt2dg.f.
.SS "character \fBjt2dg::title\fP"
.PP
Definition at line 20 of file jt2dg.f.
.SS "real*8 \fBjt2dg::zdim\fP"
.PP
Definition at line 19 of file jt2dg.f.
.SS "real*8,dimension(ngpz) \fBjt2dg::zgr\fP"
.PP
Definition at line 18 of file jt2dg.f.
.SS "real*8 \fBjt2dg::zma\fP"
.PP
Definition at line 19 of file jt2dg.f.
.SS "real*8 \fBjt2dg::zmsmid\fP"
.PP
Definition at line 19 of file jt2dg.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
