.TH "src/nk2dg.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/nk2dg.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBnk2dg\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBnk2dg::pfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBnk2dg::rgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBnk2dg::zgr\fP"
.br
.ti -1c
.RI "real *8 \fBnk2dg::rmin\fP"
.br
.ti -1c
.RI "real *8 \fBnk2dg::zmin\fP"
.br
.ti -1c
.RI "real *8 \fBnk2dg::rmax\fP"
.br
.ti -1c
.RI "real *8 \fBnk2dg::zmax\fP"
.br
.ti -1c
.RI "real *8 \fBnk2dg::delr\fP"
.br
.ti -1c
.RI "real *8 \fBnk2dg::delz\fP"
.br
.ti -1c
.RI "real *8 \fBnk2dg::psilim\fP"
.br
.ti -1c
.RI "real *8 \fBnk2dg::btorc\fP"
.br
.ti -1c
.RI "real *8 \fBnk2dg::rcntc\fP"
.br
.ti -1c
.RI "real *8 \fBnk2dg::fg\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
