.TH "nkn2dg" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nkn2dg \- Translation of equilibrium data from Naka to dg-compatible format.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBpfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBrgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBzgr\fP"
.br
.ti -1c
.RI "real *8 \fBrmin\fP"
.br
.ti -1c
.RI "real *8 \fBzmin\fP"
.br
.ti -1c
.RI "real *8 \fBrmax\fP"
.br
.ti -1c
.RI "real *8 \fBzmax\fP"
.br
.ti -1c
.RI "real *8 \fBdelr\fP"
.br
.ti -1c
.RI "real *8 \fBdelz\fP"
.br
.ti -1c
.RI "real *8 \fBpsilim\fP"
.br
.ti -1c
.RI "real *8 \fBbtorc\fP"
.br
.ti -1c
.RI "real *8 \fBrcntc\fP"
.br
.ti -1c
.RI "real *8 \fBfg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Translation of equilibrium data from Naka to dg-compatible format. 

arg1: input equilibrium file name
.PP
arg2: output equilibrium file name
.PP
\fBVersion:\fP
.RS 4
2006-09-19 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "real*8 \fBnkn2dg::btorc\fP"
.PP
Definition at line 18 of file nkn2dg.f.
.SS "real*8 \fBnkn2dg::delr\fP"
.PP
Definition at line 18 of file nkn2dg.f.
.SS "real*8 \fBnkn2dg::delz\fP"
.PP
Definition at line 18 of file nkn2dg.f.
.SS "real*8 \fBnkn2dg::fg\fP"
.PP
Definition at line 18 of file nkn2dg.f.
.SS "real*8,dimension(ngpr,ngpz) \fBnkn2dg::pfm\fP"
.PP
Definition at line 17 of file nkn2dg.f.
.SS "real*8 \fBnkn2dg::psilim\fP"
.PP
Definition at line 18 of file nkn2dg.f.
.SS "real*8 \fBnkn2dg::rcntc\fP"
.PP
Definition at line 18 of file nkn2dg.f.
.SS "real*8,dimension(ngpr) \fBnkn2dg::rgr\fP"
.PP
Definition at line 17 of file nkn2dg.f.
.SS "real*8 \fBnkn2dg::rmax\fP"
.PP
Definition at line 18 of file nkn2dg.f.
.SS "real*8 \fBnkn2dg::rmin\fP"
.PP
Definition at line 18 of file nkn2dg.f.
.SS "real*8,dimension(ngpz) \fBnkn2dg::zgr\fP"
.PP
Definition at line 17 of file nkn2dg.f.
.SS "real*8 \fBnkn2dg::zmax\fP"
.PP
Definition at line 18 of file nkn2dg.f.
.SS "real*8 \fBnkn2dg::zmin\fP"
.PP
Definition at line 18 of file nkn2dg.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
