.TH "src/nkn2dg.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/nkn2dg.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBnkn2dg\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBnkn2dg::pfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBnkn2dg::rgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBnkn2dg::zgr\fP"
.br
.ti -1c
.RI "real *8 \fBnkn2dg::rmin\fP"
.br
.ti -1c
.RI "real *8 \fBnkn2dg::zmin\fP"
.br
.ti -1c
.RI "real *8 \fBnkn2dg::rmax\fP"
.br
.ti -1c
.RI "real *8 \fBnkn2dg::zmax\fP"
.br
.ti -1c
.RI "real *8 \fBnkn2dg::delr\fP"
.br
.ti -1c
.RI "real *8 \fBnkn2dg::delz\fP"
.br
.ti -1c
.RI "real *8 \fBnkn2dg::psilim\fP"
.br
.ti -1c
.RI "real *8 \fBnkn2dg::btorc\fP"
.br
.ti -1c
.RI "real *8 \fBnkn2dg::rcntc\fP"
.br
.ti -1c
.RI "real *8 \fBnkn2dg::fg\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
