.TH "src/open_files.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/open_files.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBopen_files\fP (outstring)"
.br
.RI "\fIutility routine for opening files \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "subroutine open_files (character*(*) outstring)"
.PP
utility routine for opening files 
.PP
argument 1 to the program (via getarg) is attached to file unit 1 argument 2 to the program (via getarg) is attached to file unit 2 
.PP
Definition at line 5 of file open_files.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
