.TH "src/pb2dg.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/pb2dg.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBpb2dg\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr) \fBpb2dg::fg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBpb2dg::pg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBpb2dg::ffg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBpb2dg::ppg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBpb2dg::pfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBpb2dg::rgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBpb2dg::zgr\fP"
.br
.ti -1c
.RI "real *8 \fBpb2dg::rcntc\fP"
.br
.ti -1c
.RI "real *8 \fBpb2dg::psilim\fP"
.br
.ti -1c
.RI "real *8 \fBpb2dg::btorc\fP"
.br
.ti -1c
.RI "real *8 \fBpb2dg::pi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
