.TH "pb2dg" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pb2dg \- Translation of equilibrium data from P. Barabasci into dg-compatible format.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr) \fBfg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBpg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBffg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBppg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBpfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBrgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBzgr\fP"
.br
.ti -1c
.RI "real *8 \fBrcntc\fP"
.br
.ti -1c
.RI "real *8 \fBpsilim\fP"
.br
.ti -1c
.RI "real *8 \fBbtorc\fP"
.br
.ti -1c
.RI "real *8 \fBpi\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Translation of equilibrium data from P. Barabasci into dg-compatible format. 

arg1: input equilibrium file name
.PP
arg2: output equilibrium file name
.PP
\fBVersion:\fP
.RS 4
02.09.99 19:37 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "real*8 \fBpb2dg::btorc\fP"
.PP
Definition at line 20 of file pb2dg.f.
.SS "real*8,dimension(ngpr) \fBpb2dg::ffg\fP"
.PP
Definition at line 18 of file pb2dg.f.
.SS "real*8,dimension(ngpr) \fBpb2dg::fg\fP"
.PP
Definition at line 18 of file pb2dg.f.
.SS "real*8,dimension(ngpr,ngpz) \fBpb2dg::pfm\fP"
.PP
Definition at line 19 of file pb2dg.f.
.SS "real*8,dimension(ngpr) \fBpb2dg::pg\fP"
.PP
Definition at line 18 of file pb2dg.f.
.SS "real*8 \fBpb2dg::pi\fP"
.PP
Definition at line 20 of file pb2dg.f.
.SS "real*8,dimension(ngpr) \fBpb2dg::ppg\fP"
.PP
Definition at line 18 of file pb2dg.f.
.SS "real*8 \fBpb2dg::psilim\fP"
.PP
Definition at line 20 of file pb2dg.f.
.SS "real*8 \fBpb2dg::rcntc\fP"
.PP
Definition at line 20 of file pb2dg.f.
.SS "real*8,dimension(ngpr) \fBpb2dg::rgr\fP"
.PP
Definition at line 19 of file pb2dg.f.
.SS "real*8,dimension(ngpz) \fBpb2dg::zgr\fP"
.PP
Definition at line 19 of file pb2dg.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
