.TH "src/prinequ.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/prinequ.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBprinequ\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr) \fBprinequ::fg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBprinequ::pg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBprinequ::ffg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBprinequ::ppg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBprinequ::pfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBprinequ::rgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBprinequ::zgr\fP"
.br
.ti -1c
.RI "real *8 \fBprinequ::rdim\fP"
.br
.ti -1c
.RI "real *8 \fBprinequ::zdim\fP"
.br
.ti -1c
.RI "real *8 \fBprinequ::rcntc\fP"
.br
.ti -1c
.RI "real *8 \fBprinequ::redge\fP"
.br
.ti -1c
.RI "real *8 \fBprinequ::zmsmid\fP"
.br
.ti -1c
.RI "real *8 \fBprinequ::rma\fP"
.br
.ti -1c
.RI "real *8 \fBprinequ::zma\fP"
.br
.ti -1c
.RI "real *8 \fBprinequ::psimin\fP"
.br
.ti -1c
.RI "real *8 \fBprinequ::psilim\fP"
.br
.ti -1c
.RI "real *8 \fBprinequ::btorc\fP"
.br
.ti -1c
.RI "character \fBprinequ::title\fP"
.br
.ti -1c
.RI "character \fBprinequ::date\fP"
.br
.ti -1c
.RI "character \fBprinequ::page\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
