.TH "prinequ" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prinequ \- Printout of dg-compatible equilibrium data in a table.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr) \fBfg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBpg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBffg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBppg\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBpfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBrgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBzgr\fP"
.br
.ti -1c
.RI "real *8 \fBrdim\fP"
.br
.ti -1c
.RI "real *8 \fBzdim\fP"
.br
.ti -1c
.RI "real *8 \fBrcntc\fP"
.br
.ti -1c
.RI "real *8 \fBredge\fP"
.br
.ti -1c
.RI "real *8 \fBzmsmid\fP"
.br
.ti -1c
.RI "real *8 \fBrma\fP"
.br
.ti -1c
.RI "real *8 \fBzma\fP"
.br
.ti -1c
.RI "real *8 \fBpsimin\fP"
.br
.ti -1c
.RI "real *8 \fBpsilim\fP"
.br
.ti -1c
.RI "real *8 \fBbtorc\fP"
.br
.ti -1c
.RI "character \fBtitle\fP"
.br
.ti -1c
.RI "character \fBdate\fP"
.br
.ti -1c
.RI "character \fBpage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Printout of dg-compatible equilibrium data in a table. 

The file is read from standard input and the result sent to the standard output
.PP
\fBVersion:\fP
.RS 4
02.09.99 14:21 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "real*8 \fBprinequ::btorc\fP"
.PP
Definition at line 21 of file prinequ.f.
.SS "character \fBprinequ::date\fP"
.PP
Definition at line 22 of file prinequ.f.
.SS "real*8,dimension(ngpr) \fBprinequ::ffg\fP"
.PP
Definition at line 19 of file prinequ.f.
.SS "real*8,dimension(ngpr) \fBprinequ::fg\fP"
.PP
Definition at line 19 of file prinequ.f.
.SS "character \fBprinequ::page\fP"
.PP
Definition at line 22 of file prinequ.f.
.SS "real*8,dimension(ngpr,ngpz) \fBprinequ::pfm\fP"
.PP
Definition at line 20 of file prinequ.f.
.SS "real*8,dimension(ngpr) \fBprinequ::pg\fP"
.PP
Definition at line 19 of file prinequ.f.
.SS "real*8,dimension(ngpr) \fBprinequ::ppg\fP"
.PP
Definition at line 19 of file prinequ.f.
.SS "real*8 \fBprinequ::psilim\fP"
.PP
Definition at line 21 of file prinequ.f.
.SS "real*8 \fBprinequ::psimin\fP"
.PP
Definition at line 21 of file prinequ.f.
.SS "real*8 \fBprinequ::rcntc\fP"
.PP
Definition at line 21 of file prinequ.f.
.SS "real*8 \fBprinequ::rdim\fP"
.PP
Definition at line 21 of file prinequ.f.
.SS "real*8 \fBprinequ::redge\fP"
.PP
Definition at line 21 of file prinequ.f.
.SS "real*8,dimension(ngpr) \fBprinequ::rgr\fP"
.PP
Definition at line 20 of file prinequ.f.
.SS "real*8 \fBprinequ::rma\fP"
.PP
Definition at line 21 of file prinequ.f.
.SS "character \fBprinequ::title\fP"
.PP
Definition at line 22 of file prinequ.f.
.SS "real*8 \fBprinequ::zdim\fP"
.PP
Definition at line 21 of file prinequ.f.
.SS "real*8,dimension(ngpz) \fBprinequ::zgr\fP"
.PP
Definition at line 20 of file prinequ.f.
.SS "real*8 \fBprinequ::zma\fP"
.PP
Definition at line 21 of file prinequ.f.
.SS "real*8 \fBprinequ::zmsmid\fP"
.PP
Definition at line 21 of file prinequ.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
