.TH "src/pt2dg.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/pt2dg.f \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'pt2dg.inc'\fP
.br

.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBpt2dg\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBTRINWT\fP"
.br
.ti -1c
.RI "subroutine \fBBPOLRZ\fP"
.br
.ti -1c
.RI "subroutine \fBWBPOLRZ\fP"
.br
.ti -1c
.RI "subroutine \fBwreqdg\fP (lun, ngpr, ngpz, iret, nr, nz, psib, btf, rtf, rgr, zgr, pfm)"
.br
.RI "\fIWrite the equilibrium data in the dg-compatible format. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "logical \fBpt2dg::ex\fP"
.br
.ti -1c
.RI "logical \fBpt2dg::exi\fP"
.br
.ti -1c
.RI "character *256 \fBpt2dg::in_mesh\fP"
.br
.ti -1c
.RI "character *256 \fBpt2dg::in_psi\fP"
.br
.ti -1c
.RI "character *256 \fBpt2dg::out_file\fP"
.br
.ti -1c
.RI "character *256 \fBpt2dg::hlp_txt\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "subroutine BPOLRZ ()"
.PP
Definition at line 513 of file pt2dg.f.
.SS "subroutine TRINWT ()"
.PP
Definition at line 432 of file pt2dg.f.
.SS "subroutine WBPOLRZ ()"
.PP
Definition at line 603 of file pt2dg.f.
.SS "subroutine wreqdg (integer lun, integer ngpr, integer ngpz, integer iret, integer nr, integer nz, real*8 psib, real*8 btf, real*8 rtf, real*8,dimension(ngpr) rgr, real*8,dimension(ngpz) zgr, real*8,dimension(ngpr,ngpz) pfm)"
.PP
Write the equilibrium data in the dg-compatible format. 
.PP
\fBVersion:\fP
.RS 4
23.06.97 17:23 
.RE
.PP

.PP
Definition at line 638 of file pt2dg.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
