.TH "src/rdeqpb.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rdeqpb.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBrdeqpb\fP (lun, ngpr, ngpz, iret, nr, nz, rbtor, psilim, rgr, zgr, pfm)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "subroutine rdeqpb (lun, ngpr, ngpz, iret, nr, nz, real*8 rbtor, real*8 psilim, real*8,dimension(ngpr) rgr, real*8,dimension(ngpz) zgr, real*8,dimension(ngpr, ngpz) pfm)"
.PP
Definition at line 1 of file rdeqpb.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
