.TH "src/risepsi.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/risepsi.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBrisepsi\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBrisepsi::pfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBrisepsi::rgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBrisepsi::zgr\fP"
.br
.ti -1c
.RI "real *8 \fBrisepsi::rcntc\fP"
.br
.ti -1c
.RI "real *8 \fBrisepsi::psilim\fP"
.br
.ti -1c
.RI "real *8 \fBrisepsi::btorc\fP"
.br
.ti -1c
.RI "real *8 \fBrisepsi::shift\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
