.TH "risepsi" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
risepsi \- Shift of the magnetic flux by a specified increment.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBpfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBrgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBzgr\fP"
.br
.ti -1c
.RI "real *8 \fBrcntc\fP"
.br
.ti -1c
.RI "real *8 \fBpsilim\fP"
.br
.ti -1c
.RI "real *8 \fBbtorc\fP"
.br
.ti -1c
.RI "real *8 \fBshift\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Shift of the magnetic flux by a specified increment. 

arg1: input equilibrium file name
.PP
arg2: output equilibrium file name
.PP
shift is read in from standard input
.PP
\fBVersion:\fP
.RS 4
30.01.96 21:58 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "real*8 \fBrisepsi::btorc\fP"
.PP
Definition at line 20 of file risepsi.f.
.SS "real*8,dimension(ngpr,ngpz) \fBrisepsi::pfm\fP"
.PP
Definition at line 19 of file risepsi.f.
.SS "real*8 \fBrisepsi::psilim\fP"
.PP
Definition at line 20 of file risepsi.f.
.SS "real*8 \fBrisepsi::rcntc\fP"
.PP
Definition at line 20 of file risepsi.f.
.SS "real*8,dimension(ngpr) \fBrisepsi::rgr\fP"
.PP
Definition at line 19 of file risepsi.f.
.SS "real*8 \fBrisepsi::shift\fP"
.PP
Definition at line 20 of file risepsi.f.
.SS "real*8,dimension(ngpz) \fBrisepsi::zgr\fP"
.PP
Definition at line 19 of file risepsi.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
