.TH "src/shotfile2dg.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/shotfile2dg.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBshotfile2dg\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "integer \fBlnblnk\fP (string)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr) \fBshotfile2dg::gpr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBshotfile2dg::gpz\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBshotfile2dg::pfmd\fP"
.br
.ti -1c
.RI "real *8 \fBshotfile2dg::rcntc\fP"
.br
.ti -1c
.RI "real *8 \fBshotfile2dg::btorc\fP"
.br
.ti -1c
.RI "real *8 \fBshotfile2dg::psilim\fP"
.br
.ti -1c
.RI "character *256 \fBshotfile2dg::arg\fP"
.br
.ti -1c
.RI "character *256 \fBshotfile2dg::filename\fP"
.br
.ti -1c
.RI "character \fBshotfile2dg::expnam\fP"
.br
.ti -1c
.RI "character \fBshotfile2dg::dianam\fP"
.br
.ti -1c
.RI "integer \fBshotfile2dg::nshot\fP"
.br
.ti -1c
.RI "integer \fBshotfile2dg::nedit\fP"
.br
.ti -1c
.RI "integer \fBshotfile2dg::iarg\fP"
.br
.ti -1c
.RI "integer \fBshotfile2dg::iargc\fP"
.br
.ti -1c
.RI "integer \fBshotfile2dg::lnblnk\fP"
.br
.ti -1c
.RI "real \fBshotfile2dg::tshot\fP"
.br
.ti -1c
.RI "integer \fBshotfile2dg::mdim\fP"
.br
.ti -1c
.RI "integer \fBshotfile2dg::lpfxdim\fP"
.br
.ti -1c
.RI "integer \fBshotfile2dg::lin\fP"
.br
.ti -1c
.RI "real, dimension(0:mdim) \fBshotfile2dg::ri\fP"
.br
.ti -1c
.RI "real, dimension(0:mdim) \fBshotfile2dg::zj\fP"
.br
.ti -1c
.RI "real, dimension(0:mdim, 0:mdim) \fBshotfile2dg::pfm\fP"
.br
.ti -1c
.RI "real, dimension(0:lpfxdim) \fBshotfile2dg::pfxx\fP"
.br
.ti -1c
.RI "real, dimension(0:lpfxdim) \fBshotfile2dg::rpfx\fP"
.br
.ti -1c
.RI "real, dimension(0:lpfxdim) \fBshotfile2dg::zpfx\fP"
.br
.ti -1c
.RI "real, dimension(lin) \fBshotfile2dg::rin\fP"
.br
.ti -1c
.RI "real, dimension(lin) \fBshotfile2dg::zin\fP"
.br
.ti -1c
.RI "real, dimension(lin) \fBshotfile2dg::br\fP"
.br
.ti -1c
.RI "real, dimension(lin) \fBshotfile2dg::bz\fP"
.br
.ti -1c
.RI "real, dimension(lin) \fBshotfile2dg::bt\fP"
.br
.ti -1c
.RI "real, dimension(lin) \fBshotfile2dg::fpf\fP"
.br
.ti -1c
.RI "real, dimension(lin) \fBshotfile2dg::fjp\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "integer lnblnk (character*(*) string)"
.PP
Definition at line 129 of file shotfile2dg.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
