.TH "src/sst2dg.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sst2dg.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBsst2dg\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr) \fBsst2dg::gpr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBsst2dg::gpz\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpf) \fBsst2dg::pfl\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpf) \fBsst2dg::pc\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpf) \fBsst2dg::pcd\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpf) \fBsst2dg::pr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpf) \fBsst2dg::prd\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpf) \fBsst2dg::q\fP"
.br
.ti -1c
.RI "real *8, dimension(3) \fBsst2dg::apf\fP"
.br
.ti -1c
.RI "real *8, dimension(3) \fBsst2dg::xpf\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBsst2dg::pfm\fP"
.br
.ti -1c
.RI "real *8 \fBsst2dg::rcntc\fP"
.br
.ti -1c
.RI "real *8 \fBsst2dg::btorc\fP"
.br
.ti -1c
.RI "real *8 \fBsst2dg::Bt\fP"
.br
.ti -1c
.RI "real *8, dimension(6) \fBsst2dg::derivative\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
