.TH "sst2dg" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sst2dg \- Translation of efit equilibrium data into dg-compatible format.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr) \fBgpr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBgpz\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpf) \fBpfl\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpf) \fBpc\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpf) \fBpcd\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpf) \fBpr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpf) \fBprd\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpf) \fBq\fP"
.br
.ti -1c
.RI "real *8, dimension(3) \fBapf\fP"
.br
.ti -1c
.RI "real *8, dimension(3) \fBxpf\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBpfm\fP"
.br
.ti -1c
.RI "real *8 \fBrcntc\fP"
.br
.ti -1c
.RI "real *8 \fBbtorc\fP"
.br
.ti -1c
.RI "real *8 \fBBt\fP"
.br
.ti -1c
.RI "real *8, dimension(6) \fBderivative\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Translation of efit equilibrium data into dg-compatible format. 

arg1: input equilibrium file name
.PP
arg2: output equilibrium file name
.PP
This is a special variant of the standard efit-to-dg converter for SST where some information is hard-coded!
.PP
\fBVersion:\fP
.RS 4
16.11.95 20:04 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "real*8,dimension(3) \fBsst2dg::apf\fP"
.PP
Definition at line 21 of file sst2dg.f.
.SS "real*8 \fBsst2dg::Bt\fP"
.PP
Definition at line 26 of file sst2dg.f.
.SS "real*8 \fBsst2dg::btorc\fP"
.PP
Definition at line 25 of file sst2dg.f.
.SS "real*8,dimension(6) \fBsst2dg::derivative\fP"
.PP
Definition at line 26 of file sst2dg.f.
.SS "real*8,dimension(ngpr) \fBsst2dg::gpr\fP"
.PP
Definition at line 21 of file sst2dg.f.
.SS "real*8,dimension(ngpz) \fBsst2dg::gpz\fP"
.PP
Definition at line 21 of file sst2dg.f.
.SS "real*8,dimension(ngpf) \fBsst2dg::pc\fP"
.PP
Definition at line 21 of file sst2dg.f.
.SS "real*8,dimension(ngpf) \fBsst2dg::pcd\fP"
.PP
Definition at line 21 of file sst2dg.f.
.SS "real*8,dimension(ngpf) \fBsst2dg::pfl\fP"
.PP
Definition at line 21 of file sst2dg.f.
.SS "real*8,dimension(ngpr,ngpz) \fBsst2dg::pfm\fP"
.PP
Definition at line 24 of file sst2dg.f.
.SS "real*8,dimension(ngpf) \fBsst2dg::pr\fP"
.PP
Definition at line 21 of file sst2dg.f.
.SS "real*8,dimension(ngpf) \fBsst2dg::prd\fP"
.PP
Definition at line 21 of file sst2dg.f.
.SS "real*8,dimension(ngpf) \fBsst2dg::q\fP"
.PP
Definition at line 21 of file sst2dg.f.
.SS "real*8 \fBsst2dg::rcntc\fP"
.PP
Definition at line 25 of file sst2dg.f.
.SS "real*8,dimension(3) \fBsst2dg::xpf\fP"
.PP
Definition at line 21 of file sst2dg.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
