.TH "src/vr2dg.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/vr2dg.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBvr2dg\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBvr2dg::pfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBvr2dg::rgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBvr2dg::zgr\fP"
.br
.ti -1c
.RI "real *8 \fBvr2dg::rcntc\fP"
.br
.ti -1c
.RI "real *8 \fBvr2dg::psilim\fP"
.br
.ti -1c
.RI "real *8 \fBvr2dg::btorc\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
