.TH "vr2dg" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vr2dg \- Translation of TdeV equilibrium data into dg-compatible format.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "real *8, dimension(ngpr, ngpz) \fBpfm\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpr) \fBrgr\fP"
.br
.ti -1c
.RI "real *8, dimension(ngpz) \fBzgr\fP"
.br
.ti -1c
.RI "real *8 \fBrcntc\fP"
.br
.ti -1c
.RI "real *8 \fBpsilim\fP"
.br
.ti -1c
.RI "real *8 \fBbtorc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Translation of TdeV equilibrium data into dg-compatible format. 

arg1: input equilibrium file name
.PP
arg2: output equilibrium file name
.PP
\fBVersion:\fP
.RS 4
16.11.95 20:04 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "real*8 \fBvr2dg::btorc\fP"
.PP
Definition at line 19 of file vr2dg.f.
.SS "real*8,dimension(ngpr,ngpz) \fBvr2dg::pfm\fP"
.PP
Definition at line 18 of file vr2dg.f.
.SS "real*8 \fBvr2dg::psilim\fP"
.PP
Definition at line 19 of file vr2dg.f.
.SS "real*8 \fBvr2dg::rcntc\fP"
.PP
Definition at line 19 of file vr2dg.f.
.SS "real*8,dimension(ngpr) \fBvr2dg::rgr\fP"
.PP
Definition at line 18 of file vr2dg.f.
.SS "real*8,dimension(ngpz) \fBvr2dg::zgr\fP"
.PP
Definition at line 18 of file vr2dg.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
