.TH "src/wrefit.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wrefit.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBwrefit\fP (lun, ngpr, iret, title, date, ipestg, nr, nz, rdim, zdim, zmsmid, rcntc, redge, rma, zma, psimin, psilim, btorc, fg, pg, ffg, ppg, pfm)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "subroutine wrefit (lun, ngpr, iret, character title, character date, ipestg, nr, nz, real*8 rdim, real*8 zdim, real*8 zmsmid, real*8 rcntc, real*8 redge, real*8 rma, real*8 zma, real*8 psimin, real*8 psilim, real*8 btorc, real*8,dimension(*) fg, real*8,dimension(*) pg, real*8,dimension(*) ffg, real*8,dimension(*) ppg, real*8,dimension(ngpr,*) pfm)"
.PP
Definition at line 1 of file wrefit.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
