.TH "src/wreqdg.f" 3 "21 Jul 2008" "Version 2008-06" "DivGeo/dg/equtrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/wreqdg.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBwreqdg\fP (lun, ngpr, iret, nr, nz, psib, btf, rtf, rgr, zgr, pfm)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "subroutine wreqdg (integer lun, integer ngpr, integer iret, integer nr, integer nz, real*8 psib, real*8 btf, real*8 rtf, real*8,dimension(*) rgr, real*8,dimension(*) zgr, real*8,dimension(ngpr, *) pfm)"
.PP
Definition at line 1 of file wreqdg.f.
.SH "Author"
.PP 
Generated automatically by Doxygen for DivGeo/dg/equtrn from the source code.
