#  VERSION : 07.12.95 12:32

SHELL=/bin/sh
DG=$(OBJECTCODE)/dg
VPATH=src
MASTER=kk

include LISTOBJ

include config/compiler.${OBJECTCODE}

# EXCLUDELIST = owldummy.o
# OBJSfilt=$(filter-out ${EXCLUDELIST},${OBJS})
# DEST = $(OBJSfilt:%.o=$(OBJECTCODE)/%.o)
DEST = $(OBJS:%.o=$(OBJECTCODE)/%.o)

$(OBJECTCODE)/%.o : %.c
	 $(CC) $(CFLAGS) ${INCLUDES} -c $< -o $@

$(DG): $(DEST)
	 $(CC) $(CFLAGS) -o $@ $(DEST) $(LIBS)

all: $(DG) # $(OBJECTCODE)/res2fbr

# $(OBJECTCODE)/res2fbr:  res2fbr.c
# 	 $(CC) $< -o $@

# src/x_~fbr.c: src/divgeo.res $(OBJECTCODE)/res2fbr
# 	  $(OBJECTCODE)/res2fbr dgResources <src/divgeo.res >src/x_~fbr.c

update: clean files listobj $(OBJECTCODE)/res2fbr

clean:
	/bin/rm -rf ${OBJECTCODE}/*.o $(DG) *.bak

neat:
	/bin/rm -rf ${OBJECTCODE}/*.o *.bak

tags:
	etags src/*.c src/*.h

depend: ${OBJS:.o=.c}
	makedepend -f ${OBJECTCODE}/dependencies ${INCLUDES} $^
	mv ${OBJECTCODE}/dependencies ${OBJECTCODE}/dependencies.bak
	sed -e '3,$$s/^/${OBJECTCODE}\//' ${OBJECTCODE}/dependencies.bak > ${OBJECTCODE}/dependencies

listobj:
	@cd src ; echo "OBJS =" *.c | sed -e 's/ [^ /]*\// /g' -e 's/\.c/.o/g' -e 's/res2fbr\.o//g' > ../LISTOBJ

files:
	@rm src/*; cp $(MASTER)/*.c $(MASTER)/*.h $(MASTER)/dg.dgh $(MASTER)/divgeo.res src; cd src; rm pc_* bgi_* 1.c; true

include ${OBJECTCODE}/dependencies

