QT += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

#unix:!mac { LIBS += -Wl,-rpath=\\\$$ORIGIN/libs }

QMAKE_CXXFLAGS += -Wno-unused-function -posix -fno-rtti

RC_FILE = dg.rc
TARGET = dg3
TEMPLATE = app

HEADERS += \
    main/MainWnd.h \
    view/ViewWnd.h \
    view/ToolData.h \
    view/Modes.h \
    model/core/Model.h \
    model/core/IAction.h \
    model/core/IComponent.h \
    model/core/CoreConstants.h \
    model/core/Actions.h \
    common/strlib.h \
    common/mathlib.h \
    common/Types.h \
    common/Point.h \
    common/Macroes.h \
    common/Includes.h \
    model/diagnostics/Sources.h \
    model/diagnostics/Chords.h \
    model/flux/XPointTest.h \
    model/flux/XPointSeg.h \
    model/flux/SurfaceZone.h \
    model/flux/SurfaceEx.h \
    model/flux/GridPointSeg.h \
    model/flux/GridPointEx.h \
    model/flux/EquilDecl.h \
    model/flux/Equil.h \
    model/material/Template.h \
    model/material/Node.h \
    model/material/Element.h \
    model/mesh/MeshPoint.h \
    model/mesh/MeshElement.h \
    model/mesh/MeshDecl.h \
    model/mesh/MeshConstants.h \
    model/mesh/MeshCell.h \
    model/mesh/Mesh.h \
    model/sonnet/SonnetDecl.h \
    model/sonnet/SonnetData.h \
    model/sonnet/Separator.h \
    model/vars/VarSetDef.h \
    model/vars/VarSet.h \
    model/vars/VarDef.h \
    model/vars/VarsDecl.h \
    model/vars/VarConst.h \
    model/vars/Var.h \
    model/material/MaterialDecl.h \
    model/diagnostics/DiagnosticsDecl.h \
    view/ViewScene.h \
    view/items/IViewItem.h \
    view/items/ViewMeshElementItem.h \
    view/items/ViewMeshCellItem.h \
    view/items/ViewElementItem.h \
    view/ViewItemsDecl.h \
    view/ViewTopItemsDecl.h \
    view/items/ViewChordItem.h \
    view/items/ViewEquilItem.h \
    view/items/ViewNodeItem.h \
    view/items/ViewTemplateItem.h \
    view/items/ViewXPointTestItem.h \
    view/items/ViewXPointSegItem.h \
    view/items/ViewGridPointExItem.h \
    view/items/ViewGridPointSegItem.h \
    view/items/ViewSurfaceExItem.h \
    view/items/ViewAxesItem.h \
    view/items/ViewGridItem.h \
    view/items/ViewHighlightedRectItem.h \
    view/items/ViewRotateToolItem.h \
    view/items/ViewSonnetDataItem.h \
    view/items/ViewSeparatorItem.h \
    view/items/ViewSourceItem.h \
    view/ViewParameters.h \
    view/IViewScene.h \
    view/ViewTopScene.h \
    common/StdStringList.h \
    common/Version.h \
    main/Console.h \
    common/ShowFlags.h \
    common/Resources.Dialogs.h \
    common/Resources.Menu.h \
    common/Resources.Msg.h \
    common/Constants.h \
    common/ResourceTree.h \
    view/items/ViewMeshPointQuasiItem.h \
    common/Spline.h \
    view/items/ViewShapeItem.h \
    main/ModelInfo.h \
    common/Resources.Gui.h \
    view/items/ViewLabelItem.h \
    dialogs/DistrGraph.h \
    dialogs/DialogsDecl.h \
    main/ResourcesManager.h \
    common/Resources.Macro.h \
    model/flux/CreatorId.h \
    dialogs/DlgMoveRotate.h \
    dialogs/DlgCreateChord.h \
    dialogs/DlgCreateGridPoint.h \
    dialogs/DlgCreatePoint.h \
    dialogs/DlgImportTopology.h \
    dialogs/DlgExportElements.h \
    dialogs/DlgCreateSurface.h \
    dialogs/DlgGluePoints.h \
    dialogs/DlgGlueElems.h \
    dialogs/DlgStretch.h \
    dialogs/DlgSetAngle.h \
    view/ViewStateRecord.h \
    common/PointConverters.h \
    common/StringConverters.h \
    main/ModelViewManager.h \
    main/ResizableWidget.h \
    dialogs/DlgInvalidVars.h \
    dialogs/DlgVarsEdit.h \
    dialogs/DlgVsdList.h \
    dialogs/DlgCreateName.h \
    common/Metatypes.h \
    dialogs/DlgVsdEdit.h \
    dialogs/DlgVdEdit.h \
    dialogs/DlgVdHelpEdit.h \
    dialogs/DlgTopology.h \
    dialogs/DlgMeshHeader.h \
    dialogs/DlgOutputMode.h \
    dialogs/DlgMeshOptions.h \
    dialogs/DlgStatictics.h \
    model/core/ListContainer.h \
    model/core/IValueHolder.h \
    view/items/ViewRadialGridItem.h \
    model/core/IVarItem.h \
    model/core/IVarOrigin.h \
    model/core/IObject.h \
    common/ListExt.h \
    model/core/IObject.t.hpp \
    model/material/Element.t.hpp \
    main/ModelViewProxy.h \
    main/StringsManager.h \
    dialogs/DlgSettings.h \
    main/SettingsManager.h \
    view/ViewState.h \
    dialogs/PropertyTableWidget.h \
    main/SessionData.h \
    main/ToolsPanel.h \
    main/MouseToolPushButton.h \
    main/HelpManager.h \
    common/Resources.Help.h \
    dialogs/Assistant.h \
    dialogs/DlgAbout.h \
    dialogs/DlgVarHelp.h \
    dialogs/DlgNewModel.h \
    dialogs/DlgProgress.h \
    common/Resources.Log.h \
    view/items/ViewChordRadialTopItem.h \
    view/items/ViewElementRadialTopItem.h \
    view/items/ViewMeshRadialTopItem.h \
    view/items/ViewSourceRadialTopItem.h \
    view/items/ViewChordTopItem.h \
    view/items/ViewLegendItem.h \
    view/items/ViewCommentItem.h \
    model/diagnostics/Comment.h \
    dialogs/DlgCommentEdit.h \
    main/UserPreferences.h \
    main/ProjectSettings.h \
    model/core/VarsManager.h \
    model/flux/FluxModel.h \
    model/flux/Topology.h \
    model/core/IManager.h \
    model/core/DgTokens.h \
    main/ModelTree.h \
    main/ActionStackInfo.h \
    model/core/ActionStack.h \
    common/IModelAgent.h \
    main/ModelAgent.h \
    common/UpdateInfo.h

SOURCES += \
    main/MainWnd.Tools.cpp \
    main/MainWnd.Slots.cpp \
    main/MainWnd.Draw.cpp \
    main/MainWnd.cpp \
    view/ViewWnd.Draw.cpp \
    view/ViewWnd.cpp \
    model/core/Model.Write.cpp \
    model/core/Model.Read.cpp \
    model/core/Model.Objects.cpp \
    model/core/Model.cpp \
    model/core/CoreConstants.cpp \
    model/core/Actions.Equil.cpp \
    model/core/Actions.cpp \
    common/strlib.cpp \
    common/mathlib.cpp \
    model/diagnostics/Sources.cpp \
    model/diagnostics/Chords.cpp \
    model/flux/XPointTest.cpp \
    model/flux/XPointSeg.cpp \
    model/flux/SurfaceZone.cpp \
    model/flux/SurfaceEx.cpp \
    model/flux/GridPointSeg.cpp \
    model/flux/GridPointEx.cpp \
    model/flux/Equil.cpp \
    model/material/Template.cpp \
    model/material/Node.cpp \
    model/material/Element.cpp \
    model/mesh/MeshPoint.cpp \
    model/mesh/MeshElement.cpp \
    model/mesh/MeshCell.cpp \
    model/mesh/Mesh.cpp \
    model/sonnet/SonnetData.cpp \
    model/sonnet/Separator.cpp \
    model/vars/VarSetDef.cpp \
    model/vars/VarSet.cpp \
    model/vars/VarDef.cpp \
    model/vars/VarConst.cpp \
    model/vars/Var.cpp \
    model/core/Actions.Material.cpp \
    main/main.cpp \
    view/ViewScene.cpp \
    view/items/IViewItem.cpp \
    view/items/ViewMeshElementItem.cpp \
    view/items/ViewMeshCellItem.cpp \
    view/items/ViewElementItem.cpp \
    view/items/ViewChordItem.cpp \
    view/items/ViewEquilItem.cpp \
    view/items/ViewNodeItem.cpp \
    view/items/ViewTemplateItem.cpp \
    view/items/ViewXPointTestItem.cpp \
    view/items/ViewXPointSegItem.cpp \
    view/items/ViewGridPointExItem.cpp \
    view/items/ViewGridPointSegItem.cpp \
    view/items/ViewSurfaceExItem.cpp \
    view/items/ViewAxesItem.cpp \
    view/items/ViewGridItem.cpp \
    view/items/ViewHighlightedRectItem.cpp \
    view/items/ViewRotateToolItem.cpp \
    view/items/ViewSonnetDataItem.cpp \
    view/items/ViewSeparatorItem.cpp \
    view/items/ViewSourceItem.cpp \
    view/ViewParameters.cpp \
    view/IViewScene.cpp \
    view/ViewTopScene.cpp \
    main/Console.cpp \
    model/flux/Equil.Splines.cpp \
    view/ViewWnd.Mouse.cpp \
    view/ViewWnd.Tools.Geometry.cpp \
    view/ViewWnd.Tools.Helpers.cpp \
    view/ViewWnd.Tools.Objects.cpp \
    view/ViewWnd.Tools.Transform.cpp \
    common/ShowFlags.cpp \
    common/Spline.cpp \
    view/items/ViewShapeItem.cpp \
    view/ViewWnd.Tools.Mesh.cpp \
    main/ModelInfo.cpp \
    main/MainWnd.Slots.File.cpp \
    main/MainWnd.Slots.Edit.cpp \
    view/items/ViewLabelItem.cpp \
    dialogs/DistrGraph.cpp \
    main/ResourcesManager.cpp \
    common/ResourceTree.cpp \
    model/flux/CreatorId.cpp \
    dialogs/DlgMoveRotate.cpp \
    dialogs/DlgCreateChord.cpp \
    dialogs/DlgCreateGridPoint.cpp \
    dialogs/DlgCreatePoint.cpp \
    dialogs/DlgCreateSurface.cpp \
    dialogs/DlgGluePoints.cpp \
    dialogs/DlgGlueElems.cpp \
    dialogs/DlgStretch.cpp \
    dialogs/DlgSetAngle.cpp \
    main/MainWnd.Slots.View.cpp \
    main/MainWnd.Slots.Command.cpp \
    common/PointConverters.cpp \
    common/StringConverters.cpp \
    main/ModelViewManager.cpp \
    dialogs/DlgInvalidVars.cpp \
    dialogs/DlgVarsEdit.cpp \
    main/MainWnd.Slots.Variables.cpp \
    main/MainWnd.Slots.Options.cpp \
    dialogs/DlgVsdList.cpp \
    dialogs/DlgCreateName.cpp \
    dialogs/DlgVsdEdit.cpp \
    dialogs/DlgVdEdit.cpp \
    dialogs/DlgVdHelpEdit.cpp \
    dialogs/DlgTopology.cpp \
    dialogs/DlgMeshHeader.cpp \
    dialogs/DlgOutputMode.cpp \
    dialogs/DlgMeshOptions.cpp \
    dialogs/DlgStatictics.cpp \
    model/core/IAction.cpp \
    common/Point.cpp \
    model/core/Actions.Vars.cpp \
    view/items/ViewRadialGridItem.cpp \
    model/core/IVarOrigin.cpp \
    model/core/IVarItem.cpp \
    model/core/IObject.cpp \
    main/ModelViewProxy.cpp \
    dialogs/DlgSettings.cpp \
    main/SettingsManager.cpp \
    dialogs/PropertyTableWidget.cpp \
    main/StringsManager.Menus.cpp \
    main/StringsManager.Strings.cpp \
    main/StringsManager.Dialogs.cpp \
    main/StringsManager.Gui.cpp \
    main/ToolsPanel.cpp \
    main/HelpManager.cpp \
    dialogs/Assistant.cpp \
    dialogs/DlgAbout.cpp \
    dialogs/DlgVarHelp.cpp \
    dialogs/DlgNewModel.cpp \
    main/StringsManager.Log.cpp \
    view/items/ViewChordRadialTopItem.cpp \
    view/items/ViewElementRadialTopItem.cpp \
    view/items/ViewMeshRadialTopItem.cpp \
    view/items/ViewSourceRadialTopItem.cpp \
    view/items/ViewChordTopItem.cpp \
    view/items/ViewLegendItem.cpp \
    view/items/ViewCommentItem.cpp \
    model/diagnostics/Comment.cpp \
    dialogs/DlgCommentEdit.cpp \
    main/UserPreferences.cpp \
    main/ProjectSettings.cpp \
    model/core/VarsManager.cpp \
    model/core/VarsManager.InOut.cpp \
    model/core/VarsManager.Check.cpp \
    model/flux/FluxModel.cpp \
    model/flux/Topology.cpp \
    model/core/DgTokens.cpp \
    model/core/IManager.cpp \
    model/flux/FluxModel.Output.cpp \
    model/flux/Topology.InOut.cpp \
    model/flux/Equil.InOut.cpp \
    model/flux/FluxModel.Surfaces.cpp \
    model/flux/FluxModel.GridPoints.cpp \
    model/flux/Topology.Zones.cpp \
    model/flux/Topology.Segments.cpp \
    model/flux/Topology.XPoints.cpp \
    model/flux/Topology.Separatrix.cpp \
    main/ModelTree.cpp \
    main/ModelTree.Branches.cpp \
    main/ActionStackInfo.cpp \
    model/core/ActionStack.cpp \
    main/ModelAgent.cpp \
    common/UpdateInfo.cpp

OTHER_FILES += \
    dg.rc \
    ../strings.dgr \
    ../help.dgh \
    ../config.dgc

RESOURCES += \
    dg.qrc


