#ifndef GUICONSTANTS_H
#define GUICONSTANTS_H

#include "Resources.Macro.h"

struct MouseTools {
  enum EMouseTool
  {
    ZOOMPAN         = 0x010,
    MARK            = 0x020,
    EXAMINE         = 0x030,

    ROTATE          = 0x040,
    STRETCH         = 0x050,

    MOVE            = 0x060,
    DELETE          = 0x070,

    ADDELEMENT      = 0x110,
    ADDSOURCES      = 0x120,
    ADDCHORDS       = 0x130,
    ADDSURFACE      = 0x140,
    ADDGRIDPOINT    = 0x150,

    SPLITELEMENT    = 0x210,
    JOINELEMENTS    = 0x220,
    CONNECTPOINTS   = 0x230,
    REPOSITION      = 0x240,
    REVERSENORMALS  = 0x250,

    MOVEMESHPOINT   = 0x260,
    SETXPOINT       = 0x270,

    ADJUSTCHORD     = 0x310,
    EXTENDCHORD     = 0x320,

    COMMENT         = 0x410,

    MASK_BUTTON     = 0x00f,
    MASK_TOOL       = 0xff0,

    DEFAULT_LEFT_TOOL   = EXAMINE,
    DEFAULT_MID_TOOL    = MARK,
    DEFAULT_RIGHT_TOOL  = ZOOMPAN
  };
};
typedef MouseTools TOOLS;
typedef MouseTools::EMouseTool ToolId;

enum EEventID
{
  DOUBLECLICK = 1,
  PRESSED     = 2,
  MOVED       = 3,
  RELEASED    = 4,
  SHIFTCLICK  = 5
};

ENUM_STRUCT( MENU )

  ENUM( FILES, 1000 )
    NEW, OPEN, SAVE, SAVEAS, SAVECOPY, OUTPUT, PRINT, EXIT

    ENUM( RECENT, 1100 ) END_ENUM

    ENUM( IMPORT, 1200 )
      TEMPLATE, EQUILIBRIUM, MESH, TOPOLOGY, SONNETGRID
    END_ENUM

    ENUM( EXPORT, 1300 )
      MESH, ELEMENT
    END_ENUM
  END_ENUM

  ENUM( EDIT, 2000 )
    UNDO, REDO, REDO_ALL, CLEAR_ASTACK, MARK_ALL_ELEMENTS, MARK_ALL_SEPARATORS,
    MARK_ALL_CHORDS, UNMARK_ALL, EXTEND_CHORDS, MOVE_ROTATE

    ENUM( CREATE, 2100 )
      POINT, SOURCE, CHORD, SURFACE, GRIDPOINTS, SEPARATORS
    END_ENUM

    ENUM( DELETE, 2200 )
      MARKED_OBJECTS, UNUSED_POINTS, VIRTUAL_SURFACES, ELEMENTS, SOURCES,
      CHORDS, SURFACES, GRIDPOINTS, SEPARATORS, EQUILIBRIUM, TEMPLATE, MESH,
      XPOINT, SONNETGRID
    END_ENUM
  END_ENUM

  ENUM( VIEW, 3000 )
    REFRESH, ZOOM_IN, ZOOM_OUT, PICTURE_VIEW, SELECTION_VIEW, PREVIOUS_VIEW,
    REMOVE_LABELS, MESH_HEADER

    ENUM( ROTATE, 3100 )
      INCREASE_ANGLE, DECREASE_ANGLE, SET_ANGLE, RECTIFY
    END_ENUM

    ENUM( STR_SHR, 3200 )
      STRETCH_HORIZONTAL, STRETCH_VERTICAL, SHRINK_HORIZONTAL,
      SHRINK_VERTICAL, STRETCH, JUSTIFY
    END_ENUM

    ENUM( MODE, 3300 )
      STRETCH, TOPDOWN_VIEW, RADIAL_GRID, COLORED_EQUIL
    END_ENUM

    ENUM( DISPLAY, 3400 )
      NODES, IRRNODES, ELEMENTS, SOURCES, CHORDS, CHORDS3D, SEPARATORS,
      NORMALS, NUMBERS, SURFACES, GRIDPOINTS, MESH, MESHDETAILS, EQUILIBRIUM,
      TEMPLATE, AXES, GRID, SONNETGRID, XPOINTS, COMMENTS
    END_ENUM
  END_ENUM

  ENUM( COMMANDS, 4000 )
    RENUMBER_ELEMENTS, CHECK_VARIABLES, REBUILD_CARRE_OBJECTS, FIND_XPOINTS,
    FIND_XPOINTSEGS, EDIT_TOPOLOGY, UPDATE_TOPOLOGY, TEST

    ENUM( CONVERT, 4100 )
      TEMPLATE_TO_ELEMENTS, ELEMENTS_TO_CHORDS, CHORDS_TO_ELEMENTS
    END_ENUM

    ENUM( SIMPLIFY, 4200 )
      FILL_GAPS, MERGE_SPLIT_ELEMENTS

      ENUM( LINEUP_NORMALS, 4210 )
        ALL, MARKED
      END_ENUM
    END_ENUM
  END_ENUM

  ENUM( VARIABLES, 5000 )
    ADD_LAYER, REMOVE_LAYER, DISPLAY_LAYER, GENERAL_SURFACE_DATA, STRUCTURE,
    GLOBAL_EIRENE_DATA

    ENUM( ADD, 5100 ) END_ENUM

    ENUM( REMOVE, 5200 ) END_ENUM
  END_ENUM

  ENUM( OPTIONS, 6000 )
    OUTPUT_MODE, MESH_EDITING, DISPLAY_MENU, DISPLAY_TOOLBAR, MANUAL_REFRESH,
    SAVE_INTERVAL, SETTINGS, PROJECT_SETTINGS

    ENUM( SETUP, 6100 )
      VARIABLES, SAVE
    END_ENUM
  END_ENUM

  ENUM( WINDOW, 7000 )
    HIDE_MENU, NEW_VIEW, CLOSE, STATISTICS, TOOLBOX

    ENUM( PANELS, 7100 )
      MODEL_INFO, ACT_INFO, VIEWS, CONSOLE, OLDTOOLS, TOOLS, TB_VIEW, TB_EDIT
    END_ENUM
  END_ENUM

  ENUM( HELP, 8000 )
    WHATS_NEW, MANUAL, USING_HELP, ON_MAIN_WINDOW, ABOUT
  END_ENUM

END_ENUM_STRUCT


#endif // GUICONSTANTS_H
