#ifndef RESOURCES_GUI_H
#define RESOURCES_GUI_H

#include "Resources.Macro.h"

#define RC_WIDGET( name, base ) ENUM_STRUCT( name ) TITLE = base,

namespace GUI {
  ENUM_STRUCT( COMMON )
    YES, NO
  END_ENUM_STRUCT

  RC_WIDGET(  MODEL_INFO, 0x010000 )
    NOT_LOADED, PROPERTY, VALUE, ID, LENGTH, POSITION, SELECTED, NO_SELECTED,
    MARKED, VARS, VARSCONT, REGULAR

    ENUM(     MODEL,      0x011000 )
      NAME, FILENAME, CREATION_TIME, TEMPLATE_FILE, NO_TEMPLATE, OUTPUT_MODE,
      SONNET, CARRE, NODE_1, NODE_2, INTARGET, POINT_1, POINT_2, BAD_CREATORID,
      UNCHANGED, CARREMODE, LISTOF, EMPTYLIST, EMPTY, IS3D, ISEND
    END_ENUM

    ENUM(     TEMPLATE,   0x011500 )
      INCR, SCALE, ANGLE
    END_ENUM

    ENUM(     TOPOLOGY,   0x012000 )
      FILENAME, TOPOLOGY_NAME, POLOIDAL, TOROIDAL,
      LEVEL, VERTICIES, START, END, ZONE, ISUSED, DIR, DIRTARGET,
      CRID, ISDRAWN, ISOK, GPZONES, ZONESIGN, ORIENT, LIMITED, INNERMOST,
      ISCLOSED, DERIVATIVE, VIRTUAL, NAME, DESCR, ORIGIN
    END_ENUM

    ENUM(     EQUIL,      0x012500 )
      FILENAME, SIZE, VALUE
    END_ENUM

    ENUM(     MESH,       0x013000 )
      FILENAME, HEADER, SIZE, SLIDING_MODE, SLIDING_THRSHLD, DOUBLE_BORDER,
      FINGERPRINT, BY_SURFACES, BY_SPLINES,
      INDEX, BACKUP, CHANGED, CUTFLAG, BORDER, NEIGHBOURS,
      OUTERMOST, NUMBER, CENTER, RATIO, VERTICAL
    END_ENUM

    ENUM(     VARS,       0x014000 )
      NAME, DESCR, HELP, ENUMVALUES, MINMAXSETS, ORIGIN, VARTYPE,
      ROWCOLUMN, MULTIPLE, HASGROUP, FLAGS, TYPEFLAGS

      ENUM( VDFLAGS,      0x014100 )
        NOEXPORT, FORELEMS, FORSEPARATORS, FORSOURCES, FORCHORDS, LAYERINDEX
      END_ENUM

      ENUM( TYPEFLAGS,    0x014200 )
        HASELEMS, LOCKGROUP, SINGLE, STRUCTPART, HASCHORDS, HASMESH, TARGET,
        FILENAME
      END_ENUM

      ENUM(     TYPES,    0x014300 )
        INT, FLOAT, TEXT, FILENAME, ELEM, ELEMS, TARGET1, TARGET2, STRUCTURE,
        STRUCTPART, CHORDS, MESHCELLS, MESHELEMS, MESH_HELEMS, MESH_VELEMS, TOPVIEW
      END_ENUM

    END_ENUM

    ENUM(     TYPE,       0x015000 )
      ELEMENT, SEPARATOR, SOURCE, CHORD, NODE, MESHPOINT, MESHCELL,
      MESHELEMENT, XPOINTSEG, XPOINTTEST, SURFACEZONE, SURFACEEX,
      GRIDPOINTSEG, GRIDPOINTEX, UNKNOWN, CONTAINER,
      VAR, VARSETDEF, VARSET, VARDEF, TEMPLATE,
      MODEL, MESH, TOPOLOGY, EQUIL
    END_ENUM

    ENUM(     ACTIONS,    0x016000 )
      UNDOSTACK, REDOSTACK,
      CHANGE_VALUE, CHANGE_OBJGROUP, MARK_OBJECT, HIGHLIGHT_OBJECT,
      ADD_X, DEL_X, CHG_X,
      PARAMETER, VALUE, ACTION
    END_ENUM

  END_ENUM_STRUCT

  RC_WIDGET(  VIEW,       0x020000 )
    SCENE, CENTER, SCALE, ANGLE, ADD
  END_ENUM_STRUCT
}

#endif // RESOURCES_GUI_H
