#ifndef RESOURCES_LOG_H
#define RESOURCES_LOG_H

#include "Resources.Macro.h"

namespace LOG {
ENUM_STRUCT( MENU )
  ENUM( FILE, 1001000 )
    NEW, OPEN, RECENT, SAVE, SAVEAS, SAVECOPY, OUTPUT, PRINT, EXIT, EDITOR

    ENUM( IMPORT, 1001200 )
      TEMPLATE, EQUILIBRIUM, MESH, TOPOLOGY, SONNETGRID
    END_ENUM

    ENUM( EXPORT, 1001300 )
      MESH, ELEMENT
    END_ENUM
  END_ENUM

  ENUM( EDIT, 1002000 )
    UNDO, REDO, REDO_ALL, CLEAR_ASTACK, MARK_ALL_ELEMENTS, MARK_ALL_SEPARATORS,
    MARK_ALL_CHORDS, UNMARK_ALL, EXTEND_CHORDS, MOVE_ROTATE

    ENUM( CREATE, 1002100 )
      POINT, SOURCE, CHORD, SURFACE, GRIDPOINTS, SEPARATORS
    END_ENUM

    ENUM( DELETE, 1002200 )
      MARKED_OBJECTS, UNUSED_POINTS, VIRTUAL_SURFACES, ELEMENTS, SOURCES,
      CHORDS, SURFACES, GRIDPOINTS, SEPARATORS, EQUILIBRIUM, TEMPLATE, MESH,
      XPOINT, SONNETGRID
    END_ENUM
  END_ENUM

  ENUM( VIEW, 1003000 )
    REFRESH, ZOOM_IN, ZOOM_OUT, PICTURE_VIEW, SELECTION_VIEW, PREVIOUS_VIEW,
    REMOVE_LABELS, MESH_HEADER, DISPLAY

    ENUM( ROTATE, 1003100 )
      INCREASE_ANGLE, DECREASE_ANGLE, SET_ANGLE, RECTIFY
    END_ENUM

    ENUM( STR_SHR, 1003200 )
      STRETCH_HORIZONTAL, STRETCH_VERTICAL, SHRINK_HORIZONTAL,
      SHRINK_VERTICAL, STRETCH, JUSTIFY
    END_ENUM

    ENUM( MODE, 1003300 )
      STRETCH, TOPDOWN_VIEW, RADIAL_GRID, COLORED_EQUIL
    END_ENUM
  END_ENUM

  ENUM( COMMANDS, 1004000 )
    RENUMBER_ELEMENTS, CHECK_VARIABLES, REBUILD_CARRE_OBJECTS, FIND_XPOINTS,
    FIND_XPOINTSEGS, EDIT_TOPOLOGY, UPDATE_TOPOLOGY, TEST

    ENUM( CONVERT, 1004100 )
      TEMPLATE_TO_ELEMENTS, ELEMENTS_TO_CHORDS, CHORDS_TO_ELEMENTS
    END_ENUM

    ENUM( SIMPLIFY, 1004200 )
      FILL_GAPS, MERGE_SPLIT_ELEMENTS

      ENUM( LINEUP_NORMALS, 1004210 )
        ALL, MARKED
      END_ENUM
    END_ENUM
  END_ENUM

  ENUM( VARIABLES, 1005000 )
    ADD_LAYER, REMOVE_LAYER, DISPLAY_LAYER, GENERAL_SURFACE_DATA, STRUCTURE,
    GLOBAL_EIRENE_DATA
  END_ENUM

  ENUM( OPTIONS, 1006000 )
    OUTPUT_MODE, MESH_EDITING, DISPLAY_MENU, DISPLAY_TOOLBAR, MANUAL_REFRESH,
    SAVE_INTERVAL, SETTINGS, PROJECT_SETTINGS

    ENUM( SETUP, 1006100 )
      VARIABLES, SAVE
    END_ENUM
  END_ENUM

  ENUM( WINDOW, 1007000 )
    HIDE_MENU, NEW_VIEW, CLOSE, STATISTICS, TOOLBOX

    ENUM( PANELS, 1007100 )
      MODEL_INFO, ACT_INFO, VIEWS, CONSOLE, OLDTOOLS, TOOLS, TB_VIEW, TB_EDIT
    END_ENUM
  END_ENUM

  ENUM( HELP, 1008000 )
    WHATS_NEW, MANUAL, USING_HELP, ON_MAIN_WINDOW, ABOUT
  END_ENUM
END_ENUM_STRUCT

ENUM_STRUCT( TOOLS )

  ZOOMPAN         = 0x010,
  MARK            = 0x020,
  EXAMINE         = 0x030,

  ROTATE          = 0x040,
  STRETCH         = 0x050,

  MOVE            = 0x060,
  DELETE          = 0x070,

  ADDELEMENT      = 0x110,
  ADDSOURCES      = 0x120,
  ADDCHORDS       = 0x130,
  ADDSURFACE      = 0x140,
  ADDGRIDPOINT    = 0x150,

  SPLITELEMENT    = 0x210,
  JOINELEMENTS    = 0x220,
  CONNECTPOINTS   = 0x230,
  REPOSITION      = 0x240,
  REVERSENORMALS  = 0x250,

  MOVEMESHPOINT   = 0x260,
  SETXPOINT       = 0x270,

  ADJUSTCHORD     = 0x310,
  EXTENDCHORD     = 0x320,

  COMMENTS        = 0x410,

  TOOL = 2000000, SELECTED, PRESSED, SHIFTPRESSED, RELEASED, MOVED,
  LEFT_BUTTON, RIGHT_BUTTON, MIDDLE_BUTTON
END_ENUM_STRUCT
}

#endif // RESOURCES_LOG_H
