#ifndef VERSION_H
#define VERSION_H

#define DG_VERSION_MAJOR 3
#define DG_VERSION_MINOR 0
#define DG_VERSION_BUILD 1410
#define DG_VERSION_REV 0

#define QU(x) #x
#define QUH(x) QU(x)
#define DG_VERSION_STR_SHORT QUH(DG_VERSION_MAJOR) "." QUH(DG_VERSION_MINOR)
#define DG_VERSION_STR_BUILD QUH(DG_VERSION_BUILD) "." QUH(DG_VERSION_REV)
#define DG_VERSION_FULL DG_VERSION_MAJOR, DG_VERSION_MINOR, DG_VERSION_BUILD, DG_VERSION_REV
#define DG_VERSION_STR_FULL DG_VERSION_STR_SHORT "." DG_VERSION_STR_BUILD
#define DG_VERSION_STR_FULL_TITLE "v" DG_VERSION_STR_SHORT " beta (build" DG_VERSION_STR_BUILD ")"
#define DG_VERSION_OLDSTYLE 30000

#define FILE_VERSION 115
#define FILE3_VERSION 316

#endif // VERSION_H
